services:

  victoriametrics: 
    image: victoriametrics/victoria-metrics:latest
    ports:
      - "8428:8428"
    volumes:
      - vmdata:/storage
    command:
      - -storageDataPath=/storage
      # Keep metrics for 2 days
      - -retentionPeriod=2d
    restart: always
  
  # lgtm
  victorialogs: 
    image: victoriametrics/victoria-logs:latest
    ports:
      - "9428:9428"
    depends_on:
      - victoriametrics
    volumes:
      - vldata:/vlogs
    command:
      - -storageDataPath=/vlogs
      - -retentionPeriod=2d

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    volumes:
      # tells grafana where the VI and VM are. 
      - ./config/grafana-datasource.yml:/etc/grafana/provisioning/datasources/datasource.yaml
      - grafana_data:/var/lib/grafana
    environment:
      # allow grafana to query visualise and interact with VictorialMetrics
      - "GF_INSTALL_PLUGINS=victoriametrics-logs-datasource"
    depends_on:
      - victoriametrics 
      - victorialogs

  opentelemetry:
    image: otel/opentelemetry-collector-contrib
    command: ["--config=/etc/otel-collector-config.yml"]
    volumes:
      - ./config/otel-collector-config.yml:/etc/otel-collector-config.yml
    ports:
      - "4318:4318"

volumes:
  vmdata: {}
  vldata: {}
  grafana_data: {}