services:
  victoria-metrics: 
    image: victoriametrics/victoria-metrics:latest
    ports:
      - "8428:8428"
    volumes:
      - vm_data:/storage
    command:
      - -storageDataPath=/storage
      # Keep metrics for 2 days
      - -retentionPeriod=2d
  
  victoria-logs: 
    image: victoriametrics/victoria-logs:latest
    ports:
      - "9201:9201"
    depends_on:
      - victoria-metrics
    volumes:
      - vl_data:/storage
    command:
      - -storageDataPath=/storage
      - -retentionPeriod=2d

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    volumes: # to store grafana configurations, dashboards, states and etc
      - ./grafana-datasources.yaml:/etc/grafana/provisioning/datasources/datasources.yaml
      - grafana_data:/var/lib/grafana
    depends_on:
      - victoria-metrics 
      - victoria-logs

  opentelemetry:
    image: otel/opentelemetry-collector-contrib
    command: ["--config=/etc/otel-collector-config.yaml"]
    volumes:
      - ./otel-collector-config.yaml:/etc/otel-collector-config.yaml
    ports:
      - "4318:4318"

volumes:
  vm_data:
  vl_data:
  grafana_data: